export const ENV = {
  // Weather
  WEATHER_MAIN: import.meta.env.VITE_REACT_APP_WEATHER_MAIN_KEY,
  WEATHER_SERVE: import.meta.env.VITE_REACT_APP_WEATHER_SERVE_KEY,
  // KAKAO
  KAKAO_LOGIN_API_KEY: import.meta.env.VITE_KAKAO_LOGIN_API_KEY,
  KAKAO_JS_KEY: import.meta.env.VITE_REACT_APP_KAKAO_JS_KEY,
  // LOCATION
  LOCATION_API_KEY: import.meta.env.VITE_REACT_APP_LOCATION_API_KEY,
  // SERVER
  API_SERVER: import.meta.env.VITE_API_SERVER,
  // PRODUCTION
  APP_PRODUCTION: import.meta.env.VITE_APP_PRODUCTION,
};
